apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-aws-monitor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/TomerBahar22/JB-Project.git'
    path: flask-aws-monitor      
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: flask
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
